package com.wuwaconfig.app.config

import com.wuwaconfig.app.model.CvarCategory

object CvarCategorizer {
    private data class CatRule(val prefix: String, val category: CvarCategory)

    private data class CatOverride(val cvar: String, val category: CvarCategory)

    private val topLevelRules =
        listOf(
            CatRule("a.", CvarCategory.ANIMATION),
            CatRule("bbm.", CvarCategory.SYSTEM),
            CatRule("compat.", CvarCategory.SYSTEM),
            CatRule("fx.", CvarCategory.EFFECTS),
            CatRule("niagara.", CvarCategory.EFFECTS),
            CatRule("foliage.", CvarCategory.ENVIRONMENT),
            CatRule("grass.", CvarCategory.ENVIRONMENT),
            CatRule("gc.", CvarCategory.MEMORY),
            CatRule("s.", CvarCategory.TEXTURE_STREAMING),
            CatRule("sg.", CvarCategory.SCALABILITY),
            CatRule("vr.", CvarCategory.SYSTEM),
            CatRule("wp.", CvarCategory.WORLD),
            CatRule("lod.", CvarCategory.LOD_CULLING),
            CatRule("n.", CvarCategory.WORLD),
            CatRule("t.", CvarCategory.SYSTEM),
            CatRule("tick.", CvarCategory.SYSTEM),
            CatRule("slate.", CvarCategory.SYSTEM),
            CatRule("kuro.", CvarCategory.SYSTEM),
        )

    private val rSubRules =
        listOf(
            CatRule("r.shadow.", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.lightfunction", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.lightshaft", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.ambientocclusion", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.csmupdate", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.distancefield", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.capsuleshadows", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.contactshadows", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.ssgi", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.kuro.globallightquality", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.kuro.globallightshadowquality", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.reflectionenvironment", CvarCategory.ENVIRONMENT),
            CatRule("r.fog", CvarCategory.ENVIRONMENT),
            CatRule("r.volumetricfog", CvarCategory.ENVIRONMENT),
            CatRule("r.kurovolumec", CvarCategory.ENVIRONMENT),
            CatRule("r.landscape", CvarCategory.ENVIRONMENT),
            CatRule("r.kuro.foliage", CvarCategory.ENVIRONMENT),
            CatRule("r.kuro.landscapecapture", CvarCategory.ENVIRONMENT),
            CatRule("r.fogvisibilityculling", CvarCategory.ENVIRONMENT),
            CatRule("r.ssr", CvarCategory.REFLECTION),
            CatRule("r.mobile.ssr", CvarCategory.REFLECTION),
            CatRule("r.mobile.waterssr", CvarCategory.REFLECTION),
            CatRule("r.mobile.sceneobjmobilessr", CvarCategory.REFLECTION),
            CatRule("r.mobile.pixelprojectedreflectionquality", CvarCategory.REFLECTION),
            CatRule("r.kuro.enableplanarreflection", CvarCategory.REFLECTION),
            CatRule("r.bloomquality", CvarCategory.POST_PROCESS),
            CatRule("r.kurobloom", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.kurobloom", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.kuroenablefftbloom", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.kuroenabletoonfftbloom", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.kurobloomstreak", CvarCategory.POST_PROCESS),
            CatRule("r.tonemapper", CvarCategory.POST_PROCESS),
            CatRule("r.kurotonemapping", CvarCategory.POST_PROCESS),
            CatRule("r.temporalaa", CvarCategory.POST_PROCESS),
            CatRule("r.postprocessaaquality", CvarCategory.POST_PROCESS),
            CatRule("r.defaultfeature.antialiasing", CvarCategory.POST_PROCESS),
            CatRule("r.upscale", CvarCategory.POST_PROCESS),
            CatRule("r.eyeadaptationquality", CvarCategory.POST_PROCESS),
            CatRule("r.motionblurquality", CvarCategory.POST_PROCESS),
            CatRule("r.depthoffieldquality", CvarCategory.POST_PROCESS),
            CatRule("r.lensflarequality", CvarCategory.POST_PROCESS),
            CatRule("r.scenecolorfringequal", CvarCategory.POST_PROCESS),
            CatRule("r.tonemapper.grainquantization", CvarCategory.POST_PROCESS),
            CatRule("r.disabledistortion", CvarCategory.POST_PROCESS),
            CatRule("r.defaultfeature.lensflare", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.autexposure", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.radialblur", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.lguiblurtexture", CvarCategory.POST_PROCESS),
            CatRule("r.fidelityfx.fsr.rcas", CvarCategory.POST_PROCESS),
            CatRule("r.temporalaa.sharpness", CvarCategory.POST_PROCESS),
            CatRule("r.streaming.", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.texturestreaming", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.maxanisotropy", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.rendertargetpoolmin", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.anisotropicmaterials", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.kuro.toonoutline", CvarCategory.CHARACTER),
            CatRule("r.kuro.tooneye", CvarCategory.CHARACTER),
            CatRule("r.kuro.toonface", CvarCategory.CHARACTER),
            CatRule("r.kuro.skeletalm", CvarCategory.CHARACTER),
            CatRule("r.kuro.npcdisapp", CvarCategory.CHARACTER),
            CatRule("r.mobile.outlinescale", CvarCategory.CHARACTER),
            CatRule("r.mobile.treerimlight", CvarCategory.CHARACTER),
            CatRule("r.subsurfacescattering", CvarCategory.CHARACTER),
            CatRule("r.sss.", CvarCategory.CHARACTER),
            CatRule("r.skincache", CvarCategory.CHARACTER),
            CatRule("r.morphtarget", CvarCategory.CHARACTER),
            CatRule("r.bbm.", CvarCategory.CHARACTER),
            CatRule("r.clearcoatnormal", CvarCategory.CHARACTER),
            CatRule("r.basepassoutputsvelocity", CvarCategory.CHARACTER),
            CatRule("r.mobile.", CvarCategory.MOBILE),
            CatRule("r.mobilehdr", CvarCategory.MOBILE),
            CatRule("r.mobilemsaa", CvarCategory.MOBILE),
            CatRule("r.android.", CvarCategory.MOBILE),
            CatRule("r.allowhdr", CvarCategory.MOBILE),
            CatRule("r.vulkan.", CvarCategory.PIPELINE_RHI),
            CatRule("r.rhicmd", CvarCategory.PIPELINE_RHI),
            CatRule("r.pso.", CvarCategory.PIPELINE_RHI),
            CatRule("r.cachecomputepso", CvarCategory.PIPELINE_RHI),
            CatRule("r.asynccomputepso", CvarCategory.PIPELINE_RHI),
            CatRule("r.shaderpipelinecache", CvarCategory.PIPELINE_RHI),
            CatRule("r.hzbocclusion", CvarCategory.LOD_CULLING),
            CatRule("r.culldistancevolume", CvarCategory.LOD_CULLING),
            CatRule("r.minscreenradiuspercentage", CvarCategory.LOD_CULLING),
            CatRule("r.maxscreenradiuspercentage", CvarCategory.LOD_CULLING),
            CatRule("r.staticmeshloddistancescale", CvarCategory.LOD_CULLING),
            CatRule("r.screensizecullratiofactor", CvarCategory.LOD_CULLING),
            CatRule("r.kuromaxfovforlod", CvarCategory.LOD_CULLING),
            CatRule("r.allowprecomputedvisibility", CvarCategory.LOD_CULLING),
            CatRule("r.allowhardwareocclusion", CvarCategory.LOD_CULLING),
            CatRule("r.allowsoftwareocclusion", CvarCategory.LOD_CULLING),
            CatRule("r.allowocclusionqueries", CvarCategory.LOD_CULLING),
            CatRule("r.kuro.mobileism", CvarCategory.LOD_CULLING),
            CatRule("r.mdcfallback.", CvarCategory.LOD_CULLING),
            CatRule("r.mobile.enablevoidgt", CvarCategory.PERFORMANCE),
            CatRule("r.enablemeshpassprocessorscache", CvarCategory.PERFORMANCE),
            CatRule("r.finishcurrentframe", CvarCategory.PERFORMANCE),
            CatRule("r.framepace", CvarCategory.PERFORMANCE),
            CatRule("r.vsync", CvarCategory.PERFORMANCE),
            CatRule("r.useclustereddeferredshading", CvarCategory.PERFORMANCE),
            CatRule("r.parallelfrustumcull", CvarCategory.PERFORMANCE),
            CatRule("r.enablegetdynelm", CvarCategory.PERFORMANCE),
            CatRule("r.kurofi", CvarCategory.PERFORMANCE),
            CatRule("r.vrs.", CvarCategory.PERFORMANCE),
            CatRule("r.kuro.autocool", CvarCategory.THERMAL),
            CatRule("r.kuro.thermalcontrolmode", CvarCategory.THERMAL),
            CatRule("r.dontlimitonbattery", CvarCategory.THERMAL),
            CatRule("r.emitterspawnratescale", CvarCategory.EFFECTS),
            CatRule("r.afme.", CvarCategory.PERFORMANCE),
            CatRule("r.allowstaticlighting", CvarCategory.SYSTEM),
            CatRule("r.allowglobalclipplane", CvarCategory.SYSTEM),
            CatRule("r.ao", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.client.", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.kurotoonfft", CvarCategory.POST_PROCESS),
            CatRule("r.kuro.smc.obbprojectmode", CvarCategory.SYSTEM),
            CatRule("r.drawkuropplensflare", CvarCategory.POST_PROCESS),
            CatRule("r.enableaggressivepvs", CvarCategory.LOD_CULLING),
            CatRule("r.customdepth", CvarCategory.SYSTEM),
            CatRule("r.dbuffer", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.debugdisable", CvarCategory.SYSTEM),
            CatRule("r.defaultbackbuffer", CvarCategory.PIPELINE_RHI),
            CatRule("r.desktop.", CvarCategory.PIPELINE_RHI),
            CatRule("r.detailmode", CvarCategory.SYSTEM),
            CatRule("r.dof.", CvarCategory.POST_PROCESS),
            CatRule("r.earlyzpass", CvarCategory.PERFORMANCE),
            CatRule("r.enablekurotranslucentprepass", CvarCategory.SYSTEM),
            CatRule("r.fastblurthreshold", CvarCategory.POST_PROCESS),
            CatRule("r.festimation", CvarCategory.PERFORMANCE),
            CatRule("r.fidelityfx.", CvarCategory.POST_PROCESS),
            CatRule("r.filter.", CvarCategory.POST_PROCESS),
            CatRule("r.forwardshading", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.frustumcull", CvarCategory.LOD_CULLING),
            CatRule("r.gbufferformat", CvarCategory.PIPELINE_RHI),
            CatRule("r.generatelandscapegi", CvarCategory.ENVIRONMENT),
            CatRule("r.generatemeshdistancefields", CvarCategory.ENVIRONMENT),
            CatRule("r.gpucrash", CvarCategory.SYSTEM),
            CatRule("r.gpuscene", CvarCategory.PIPELINE_RHI),
            CatRule("r.gpuskin.", CvarCategory.CHARACTER),
            CatRule("r.hairstrands.", CvarCategory.CHARACTER),
            CatRule("r.imp.", CvarCategory.LOD_CULLING),
            CatRule("r.lgui.", CvarCategory.SYSTEM),
            CatRule("r.lguistenciltestenabled", CvarCategory.SYSTEM),
            CatRule("r.lightpropagationvolume", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.localexposure", CvarCategory.POST_PROCESS),
            CatRule("r.localfogvolume", CvarCategory.ENVIRONMENT),
            CatRule("r.marchingcubes.", CvarCategory.ENVIRONMENT),
            CatRule("r.materialqualitylevel", CvarCategory.SYSTEM),
            CatRule("r.materialsave", CvarCategory.SYSTEM),
            CatRule("r.meshblend.", CvarCategory.PERFORMANCE),
            CatRule("r.meshdrawcommands.", CvarCategory.PERFORMANCE),
            CatRule("r.meshstreaming", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.metal.", CvarCategory.MOBILE),
            CatRule("r.metalfx", CvarCategory.PIPELINE_RHI),
            CatRule("r.mfrc.", CvarCategory.PERFORMANCE),
            CatRule("r.minscreenradiusfor", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.neverocclusiontestdistance", CvarCategory.LOD_CULLING),
            CatRule("r.opengl.", CvarCategory.PIPELINE_RHI),
            CatRule("r.openharmony.", CvarCategory.MOBILE),
            CatRule("r.optimize", CvarCategory.SYSTEM),
            CatRule("r.particlelight", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.precomputedvisibility", CvarCategory.SYSTEM),
            CatRule("r.quantizeviewrectsize", CvarCategory.SYSTEM),
            CatRule("r.raytracing", CvarCategory.PIPELINE_RHI),
            CatRule("r.reflectioncapture", CvarCategory.ENVIRONMENT),
            CatRule("r.refractionquality", CvarCategory.POST_PROCESS),
            CatRule("r.rtrc", CvarCategory.REFLECTION),
            CatRule("r.scenecapturemax", CvarCategory.SYSTEM),
            CatRule("r.scenecolorformat", CvarCategory.PIPELINE_RHI),
            CatRule("r.sceneinfosframing.", CvarCategory.SYSTEM),
            CatRule("r.screenpercentage", CvarCategory.SYSTEM),
            CatRule("r.secondaryscreenpercentage", CvarCategory.POST_PROCESS),
            CatRule("r.selectivebasepassoutputs", CvarCategory.PERFORMANCE),
            CatRule("r.separatetranslucency", CvarCategory.POST_PROCESS),
            CatRule("r.shadercompiler.", CvarCategory.PIPELINE_RHI),
            CatRule("r.sharecustomdepth", CvarCategory.SYSTEM),
            CatRule("r.sharphereal.", CvarCategory.SYSTEM),
            CatRule("r.skeletalmesh", CvarCategory.CHARACTER),
            CatRule("r.skyatmosphere.", CvarCategory.ENVIRONMENT),
            CatRule("r.skyatmospherelut", CvarCategory.ENVIRONMENT),
            CatRule("r.skyblending", CvarCategory.ENVIRONMENT),
            CatRule("r.skylight.", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.sparsevolumetexture.", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.ssfs.", CvarCategory.CHARACTER),
            CatRule("r.stencilforloddither", CvarCategory.LOD_CULLING),
            CatRule("r.stripdepthonlytoon", CvarCategory.CHARACTER),
            CatRule("r.supportatmosphericfog", CvarCategory.ENVIRONMENT),
            CatRule("r.supportdepthonly", CvarCategory.PIPELINE_RHI),
            CatRule("r.supportlowqualitylightmaps", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.supportpointlight", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.supportreversedindexbuffers", CvarCategory.PIPELINE_RHI),
            CatRule("r.supportskyatmosphere", CvarCategory.ENVIRONMENT),
            CatRule("r.suspendworld", CvarCategory.PERFORMANCE),
            CatRule("r.translucencylightingvolumedim", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.translucencyvolume", CvarCategory.POST_PROCESS),
            CatRule("r.usekuro", CvarCategory.SYSTEM),
            CatRule("r.uselandscapesrvbuffer", CvarCategory.ENVIRONMENT),
            CatRule("r.usevisibility", CvarCategory.LOD_CULLING),
            CatRule("r.vertexcompressmeshversion", CvarCategory.SYSTEM),
            CatRule("r.vertexdeformationoutputsvelocity", CvarCategory.CHARACTER),
            CatRule("r.vertexfogging", CvarCategory.ENVIRONMENT),
            CatRule("r.viewdistancescale", CvarCategory.LOD_CULLING),
            CatRule("r.virtualtextured", CvarCategory.LIGHTING_SHADOW),
            CatRule("r.virtualtextures", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.volumetriccloud.", CvarCategory.ENVIRONMENT),
            CatRule("r.vt.", CvarCategory.TEXTURE_STREAMING),
            CatRule("r.wireframecullthreshold", CvarCategory.PERFORMANCE),
            CatRule("r.skipprenderwhen", CvarCategory.SYSTEM),
            CatRule("r.skiprenderwhen", CvarCategory.SYSTEM),
            CatRule("r.cachescenecolor", CvarCategory.SYSTEM),
        )

    private val overrides =
        listOf(
            CatOverride("compat.usedxt5normalmaps", CvarCategory.TEXTURE_STREAMING),
            CatOverride("enablenavpartition", CvarCategory.WORLD),
            CatOverride("enablesceneinfosframing", CvarCategory.SYSTEM),
            CatOverride("fx.allowgpubarticles", CvarCategory.EFFECTS),
            CatOverride("hismbatcher.enabled", CvarCategory.LOD_CULLING),
            CatOverride("kuro.collision.useseparatedbody", CvarCategory.SYSTEM),
            CatOverride("kuro.compactmatrix.enablecompactmatrixincook", CvarCategory.SYSTEM),
            CatOverride("kuro.interactiveleavestickasync", CvarCategory.ENVIRONMENT),
            CatOverride("kuro.script.enablecsharpenv", CvarCategory.SYSTEM),
            CatOverride("kuro.sharphereal.jsbridgestringispassbypointer", CvarCategory.SYSTEM),
            CatOverride("magt.enablemagt", CvarCategory.PERFORMANCE),
            CatOverride("niagara.gpuculling", CvarCategory.EFFECTS),
            CatOverride("niagara.gpudrawindirectargsbufferslack", CvarCategory.EFFECTS),
            CatOverride("niagara.gpusorting.usemaxprecision", CvarCategory.EFFECTS),
            CatOverride("sequencer.enableoldlguibindings", CvarCategory.SYSTEM),
            CatOverride("ubinstancing.enabled", CvarCategory.LOD_CULLING),
            CatOverride("ubinstancing.enableddepth", CvarCategory.LOD_CULLING),
            CatOverride("ubinstancing.enabledshaders", CvarCategory.LOD_CULLING),
            CatOverride("ubinstancing.enabledshadow", CvarCategory.LOD_CULLING),
            CatOverride("a.skinmeshsupportsrenderstatic", CvarCategory.CHARACTER),
            CatOverride("a.useswappyforframepacing", CvarCategory.PERFORMANCE),
            CatOverride("cook.skiplandscapematerialupdatecontext", CvarCategory.SYSTEM),
            CatOverride("foliage.densityscale", CvarCategory.ENVIRONMENT),
            CatOverride("foliage.lodoptimize", CvarCategory.ENVIRONMENT),
            CatOverride("grass.cull", CvarCategory.ENVIRONMENT),
            CatOverride("grass.densityscale", CvarCategory.ENVIRONMENT),
            CatOverride("kuro.lowmemlevelmask", CvarCategory.MEMORY),
            CatOverride("lod.temporallag", CvarCategory.LOD_CULLING),
            CatOverride("m.lowmemorydevicethreshold", CvarCategory.MEMORY),
            CatOverride("r.basepassoutputsvelocity", CvarCategory.PERFORMANCE),
            CatOverride("r.clientsceneinfosframing", CvarCategory.SYSTEM),
            CatOverride("r.enablegetdynelemscache", CvarCategory.PERFORMANCE),
            CatOverride("r.enablemeshpassprocessorscache", CvarCategory.PERFORMANCE),
            CatOverride("r.gpuskin.limit2boneinfluences", CvarCategory.CHARACTER),
            CatOverride("r.kuromaxfovforlod", CvarCategory.LOD_CULLING),
            CatOverride("r.minscreenradiusforcsmdepth", CvarCategory.LIGHTING_SHADOW),
            CatOverride("r.normalmapsforstaticlighting", CvarCategory.LIGHTING_SHADOW),
            CatOverride("r.overridesmallmipsallowed", CvarCategory.TEXTURE_STREAMING),
            CatOverride("r.clearscenemethod", CvarCategory.SYSTEM),
            CatOverride("r.client.contrast", CvarCategory.POST_PROCESS),
            CatOverride("r.discardunusedquality", CvarCategory.SYSTEM),
            CatOverride("r.allowhdr", CvarCategory.MOBILE),
            CatOverride("r.mobilehdr", CvarCategory.MOBILE),
            CatOverride("r.allowprecomputedvisibility", CvarCategory.LOD_CULLING),
            CatOverride("r.allowstaticlighting", CvarCategory.LIGHTING_SHADOW),
            CatOverride("r.supportsatmosphere", CvarCategory.ENVIRONMENT),
            CatOverride("r.supportstationaryskylight", CvarCategory.LIGHTING_SHADOW),
            CatOverride("r.tessellationadaptivepixelspertriangle", CvarCategory.CHARACTER),
            CatOverride("r.translucentsortpolicy", CvarCategory.SYSTEM),
            CatOverride("r.usepreexposure", CvarCategory.POST_PROCESS),
            CatOverride("r.kuro.autexposure", CvarCategory.POST_PROCESS),
            CatOverride("r.kuro.lightfadetime", CvarCategory.LIGHTING_SHADOW),
            CatOverride("r.kuro.niagarashaderversion", CvarCategory.EFFECTS),
            CatOverride("r.kuro.obbselectlod.enabled", CvarCategory.LOD_CULLING),
            CatOverride("r.kuro.prefabversion", CvarCategory.SYSTEM),
            CatOverride("r.kuro.shaderversion", CvarCategory.SYSTEM),
            CatOverride("r.kurodownsampletranslucency", CvarCategory.POST_PROCESS),
            CatOverride("r.kuromaterialqualitylevel", CvarCategory.SYSTEM),
            CatOverride("r.kuro.grassinteractionfadingspeed", CvarCategory.ENVIRONMENT),
            CatOverride("r.kuro.landscapehlodzerocheck", CvarCategory.ENVIRONMENT),
            CatOverride("r.kuro.kuroenablescreenleak", CvarCategory.SYSTEM),
        )

    private val mobileSubExceptions =
        setOf(
            "r.mobile.ssr", "r.mobile.waterssr", "r.mobile.sceneobjmobilessr",
            "r.mobile.pixelprojectedreflectionquality",
            "r.mobile.hbao", "r.mobile.hbao.blurtype", "r.mobile.hbao.largeaofactor", "r.mobile.hbao.smallaofactor",
            "r.mobile.numdynamicpointlights", "r.mobile.enablemovablespotlights",
            "r.mobile.enablemovablespotlightsshadow", "r.mobile.enablekurospotlightsshadow",
            "r.mobile.enablemovablelightcsmshaderculling", "r.mobile.enablestaticandcsmshadowreceivers",
            "r.mobile.disablelocallightspeculardistance", "r.mobile.allowmovabledirectionallights",
            "r.mobile.enablevoidgt", "r.mobile.ssao", "r.mobile.outlinescale", "r.mobile.treerimlight",
        )

    fun categorize(key: String): CvarCategory {
        val k = key.lowercase().trim()
        if (k.isBlank()) return CvarCategory.UNKNOWN

        val override = overrides.firstOrNull { k == it.cvar }
        if (override != null) return override.category

        if (k.startsWith("r.") && k.length > 2) {
            val subKey = k.substring(2)
            if (!subKey.startsWith("mobile.")) {
                val subRule = rSubRules.firstOrNull { k.startsWith(it.prefix) }
                if (subRule != null) return subRule.category
            } else {
                val exception = mobileSubExceptions.firstOrNull { k.startsWith(it) }
                if (exception == null) {
                    val subRule = rSubRules.firstOrNull { k.startsWith(it.prefix) }
                    if (subRule != null) return subRule.category
                }
                val lightShadowPrefixes =
                    listOf(
                        "ssr", "waterssr", "sceneobjmobilessr", "pixelprojectedreflectionquality",
                        "hbao", "numdynamicpointlights", "enablemovable", "enablekurospotlightsshadow",
                        "enablestaticandcsm", "disablelocallight", "allowmovabledirectional", "ssao",
                    )
                        .map { "r.mobile.$it" }
                if (lightShadowPrefixes.any { k.startsWith(it) }) return CvarCategory.LIGHTING_SHADOW
                if (k.startsWith("r.mobile.outlinescale") || k.startsWith("r.mobile.treerimlight")) return CvarCategory.CHARACTER
                return CvarCategory.MOBILE
            }

            val topRule = rSubRules.firstOrNull { k.startsWith(it.prefix) }
            if (topRule != null) return topRule.category

            val knownCategories =
                mapOf(
                    "r.shadow" to CvarCategory.LIGHTING_SHADOW,
                    "r.imp" to CvarCategory.LOD_CULLING,
                    "r.meshdrawcommands" to CvarCategory.PERFORMANCE,
                    "r.mobile" to CvarCategory.MOBILE,
                    "r.streaming" to CvarCategory.TEXTURE_STREAMING,
                    "r.bloom" to CvarCategory.POST_PROCESS,
                    "r.tonemapper" to CvarCategory.POST_PROCESS,
                    "r.temporal" to CvarCategory.POST_PROCESS,
                    "r.postprocess" to CvarCategory.POST_PROCESS,
                    "r.defaultfeature" to CvarCategory.POST_PROCESS,
                    "r.upscale" to CvarCategory.POST_PROCESS,
                    "r.eyeadaptation" to CvarCategory.POST_PROCESS,
                    "r.motionblur" to CvarCategory.POST_PROCESS,
                    "r.depthoffield" to CvarCategory.POST_PROCESS,
                    "r.lensflare" to CvarCategory.POST_PROCESS,
                    "r.scenecolorfringe" to CvarCategory.POST_PROCESS,
                    "r.distortion" to CvarCategory.POST_PROCESS,
                    "r.lightfunction" to CvarCategory.LIGHTING_SHADOW,
                    "r.lightshaft" to CvarCategory.LIGHTING_SHADOW,
                    "r.ambientocclusion" to CvarCategory.LIGHTING_SHADOW,
                    "r.ssgi" to CvarCategory.LIGHTING_SHADOW,
                    "r.ssr" to CvarCategory.REFLECTION,
                    "r.volumetricfog" to CvarCategory.ENVIRONMENT,
                    "r.fog" to CvarCategory.ENVIRONMENT,
                    "r.landscape" to CvarCategory.ENVIRONMENT,
                    "r.foliage" to CvarCategory.ENVIRONMENT,
                    "r.distancefield" to CvarCategory.LIGHTING_SHADOW,
                    "r.skincache" to CvarCategory.CHARACTER,
                    "r.morphtarget" to CvarCategory.CHARACTER,
                    "r.bbm" to CvarCategory.CHARACTER,
                    "r.vulkan" to CvarCategory.PIPELINE_RHI,
                    "r.rhicmd" to CvarCategory.PIPELINE_RHI,
                    "r.pso" to CvarCategory.PIPELINE_RHI,
                    "r.shaderpipelinecache" to CvarCategory.PIPELINE_RHI,
                    "r.kuro" to CvarCategory.SYSTEM,
                    "r.hzb" to CvarCategory.LOD_CULLING,
                    "r.cull" to CvarCategory.LOD_CULLING,
                    "r.screensize" to CvarCategory.LOD_CULLING,
                    "r.screenradius" to CvarCategory.LOD_CULLING,
                    "r.staticmesh" to CvarCategory.LOD_CULLING,
                    "r.allowprecomputed" to CvarCategory.LOD_CULLING,
                    "r.allowsoftwareocclusion" to CvarCategory.LOD_CULLING,
                    "r.vrs" to CvarCategory.PERFORMANCE,
                    "r.framepace" to CvarCategory.PERFORMANCE,
                    "r.vsync" to CvarCategory.PERFORMANCE,
                    "r.finishcurrent" to CvarCategory.PERFORMANCE,
                    "r.texture" to CvarCategory.TEXTURE_STREAMING,
                    "r.maxanisotropy" to CvarCategory.TEXTURE_STREAMING,
                    "r.rendertarget" to CvarCategory.TEXTURE_STREAMING,
                    "r.android" to CvarCategory.MOBILE,
                    "r.subsurface" to CvarCategory.CHARACTER,
                    "r.sss" to CvarCategory.CHARACTER,
                    "r.emitter" to CvarCategory.EFFECTS,
                    "r.kurofi" to CvarCategory.PERFORMANCE,
                    "r.mobilehdr" to CvarCategory.MOBILE,
                    "r.mobilemsaa" to CvarCategory.MOBILE,
                )
            val match = knownCategories.entries.firstOrNull { (prefix, _) -> k.startsWith(prefix) }
            if (match != null) return match.value
            return CvarCategory.UNKNOWN
        }

        if (k.startsWith("compat.")) return CvarCategory.SYSTEM
        if (k.startsWith("cook.")) return CvarCategory.SYSTEM

        val topRule = topLevelRules.firstOrNull { k.startsWith(it.prefix) }
        return topRule?.category ?: CvarCategory.UNKNOWN
    }
}
