package com.wuwaconfig.app.config

import com.wuwaconfig.app.model.CalculatorCharacter
import com.wuwaconfig.app.model.CalculatorResult
import com.wuwaconfig.app.model.MaterialGroup
import com.wuwaconfig.app.model.MaterialItem
import com.wuwaconfig.app.model.SkillLevelCost

/**
 * Material costs for character and weapon progression.
 *
 * Every number here is a lookup, not arithmetic: the per-phase and per-skill-level
 * cost tables in `assets/config/calculator_materials.json` come from the Fandom
 * wiki (regenerated by `tools/update_calculator_data.py`) and already account for
 * rarity, so this only decides *which* rows of those tables a level range spans
 * and *what each row's material is called*.
 *
 * Ranges are half-open on purpose. A cost table row labelled `level = n` is the
 * cost of going **from** level n **to** n+1, and an ascension row `phase = n` is
 * the cost of going from phase n-1 to n. So "level 1 through 10" is rows 1..9,
 * and "phase 0 through 6" is rows 1..6 — see [skillRows] and [ascensionRows], which
 * are the only place that convention is encoded.
 */
object MaterialCalculator {
    const val SHELL_CREDIT = "Shell Credit"

    /** Character/weapon level cap for each ascension phase index (0..6). */
    val PHASE_MAX_LEVEL = listOf(20, 40, 50, 60, 70, 80, 90)

    /** Inclusive level range a single ascension step covers. */
    fun phaseLevelRange(phase: Int): IntRange {
        val prev = if (phase <= 0) 1 else PHASE_MAX_LEVEL.getOrElse(phase - 1) { 1 }
        val next = PHASE_MAX_LEVEL.getOrElse(phase) { 90 }
        return prev..next
    }

    /**
     * Cost rows for a skill range.
     *
     * A row labelled `level = n` upgrades level n to n+1, so "level 1 to 10" is
     * rows 1..9. `from until to` is empty when the range is a no-op, which is
     * what a zero-cost result should be.
     */
    private fun skillRows(
        from: Int,
        to: Int,
    ): List<Int> = (from until to).toList()

    /**
     * Cost rows for an ascension range.
     *
     * A row labelled `phase = n` upgrades phase n-1 to n, so "phase 0 to 6" is
     * rows 1..6 — the opposite off-by-one to [skillRows], which is exactly why
     * the two are separate functions rather than one shared range helper.
     */
    private fun ascensionRows(
        from: Int,
        to: Int,
    ): List<Int> = ((from + 1)..to).toList()

    fun characterAscensionMaterials(
        characterName: String,
        fromPhase: Int,
        toPhase: Int,
    ): List<MaterialGroup> {
        val data = MaterialData.get()
        val char = data.characters[characterName] ?: return emptyList()
        val steps = ascensionRows(fromPhase, toPhase)
        val b = GroupBuilder()
        steps.forEach { phase ->
            val row = data.characterAscensionPhases.firstOrNull { it.phase == phase } ?: return@forEach
            b.add(SHELL_CREDIT, SHELL_CREDIT, row.shellCredit)
            if (row.local > 0) b.add(CATEGORY_LOCAL, char.local, row.local)
            if (row.common1 > 0) b.add(CATEGORY_COMMON, char.common.at(0), row.common1)
            if (row.common2 > 0) b.add(CATEGORY_COMMON, char.common.at(1), row.common2)
            if (row.common3 > 0) b.add(CATEGORY_COMMON, char.common.at(2), row.common3)
            if (row.common4 > 0) b.add(CATEGORY_COMMON, char.common.at(3), row.common4)
            if (row.boss > 0) b.add(CATEGORY_BOSS, char.boss, row.boss)
        }
        return b.build()
    }

    fun skillUpgradeMaterials(
        characterName: String,
        fromLevel: Int,
        toLevel: Int,
    ): List<MaterialGroup> {
        val data = MaterialData.get()
        val char = data.characters[characterName] ?: return emptyList()
        val steps = skillRows(fromLevel, toLevel)
        val b = GroupBuilder()
        steps.forEach { level ->
            val row = data.skillMainCosts.firstOrNull { it.level == level } ?: return@forEach
            b.addForteRow(row, char)
        }
        return b.build()
    }

    /**
     * The two secondary Forte tables — inherent skills and stat bonuses.
     *
     * These are the costs most calculators skip, and skipping them is not a
     * rounding error: the four rows come to 180,000 Shell Credit alone, so a
     * phase 0 -> 6 character would be reported as needing 45% less currency than
     * the game actually charges.
     *
     * They are also **not** keyed on skill level. Every row of both tables is
     * unlocked by reaching an *ascension rank* — inherent skill 1 at rank 2, stat
     * bonus 1 at rank 3, and both rank-4 rows at rank 4 — so they belong to the
     * ascension range, not the skill range. That is why this is folded into the
     * phase calculation rather than the slider.
     *
     * The player has no choice in the matter: passing a rank unlocks its row on
     * the way through, so a range that spans rank 2 owes that cost whether or
     * not the skill slider was touched. That is also why [ascensionRows] is the
     * right filter — it is exactly "ranks newly crossed by this range".
     */
    private fun secondaryForteMaterials(
        characterName: String,
        fromPhase: Int,
        toPhase: Int,
    ): List<MaterialGroup> {
        val data = MaterialData.get()
        val char = data.characters[characterName] ?: return emptyList()
        val ranksCrossed = ascensionRows(fromPhase, toPhase)
        val b = GroupBuilder()

        // The gate lives on each row as `unlockRank`, scraped from the wiki's
        // per-row comment by `tools/update_calculator_data.py`. A row with no
        // gate is available at every rank, so it is charged unconditionally —
        // only a *present* gate can exclude a row. Treating `null` as rank 0
        // instead would silently drop the whole table.
        fun addRowsWhereRankCrossed(rows: List<SkillLevelCost>) {
            rows.forEach { row ->
                val rank = row.unlockRank
                if (rank != null && rank !in ranksCrossed) return@forEach
                b.addForteRow(row, char)
            }
        }

        addRowsWhereRankCrossed(data.skillInherentCosts)
        addRowsWhereRankCrossed(data.skillStatBonusCosts)
        return b.build()
    }

    /**
     * Maps one Forte cost row onto material names.
     *
     * Shared by all three character skill tables, which have the same column
     * shape (`wsm1..4` / `dwsm1..4` / `boss`) and draw on the same per-character
     * pools. [CalculatorCharacter.skillBoss] is the right boss material for all
     * three: the separate `boss` field is the *ascension* boss drop, which
     * appears in no skill row.
     */
    private fun GroupBuilder.addForteRow(
        row: SkillLevelCost,
        char: CalculatorCharacter,
    ) {
        add(SHELL_CREDIT, SHELL_CREDIT, row.credit)
        if (row.wsm1 > 0) add(CATEGORY_SKILL, char.wsm.at(0), row.wsm1)
        if (row.wsm2 > 0) add(CATEGORY_SKILL, char.wsm.at(1), row.wsm2)
        if (row.wsm3 > 0) add(CATEGORY_SKILL, char.wsm.at(2), row.wsm3)
        if (row.wsm4 > 0) add(CATEGORY_SKILL, char.wsm.at(3), row.wsm4)
        if (row.dwsm1 > 0) add(CATEGORY_DROP, char.dwsm.at(0), row.dwsm1)
        if (row.dwsm2 > 0) add(CATEGORY_DROP, char.dwsm.at(1), row.dwsm2)
        if (row.dwsm3 > 0) add(CATEGORY_DROP, char.dwsm.at(2), row.dwsm3)
        if (row.dwsm4 > 0) add(CATEGORY_DROP, char.dwsm.at(3), row.dwsm4)
        if (row.boss > 0) add(CATEGORY_BOSS, char.skillBoss, row.boss)
    }

    fun weaponAscensionMaterials(
        weaponName: String,
        fromPhase: Int,
        toPhase: Int,
    ): List<MaterialGroup> {
        val data = MaterialData.get()
        val weapon = data.weapons[weaponName] ?: return emptyList()
        val table = data.weaponAscensionByRarity[weapon.rarity.toString()] ?: return emptyList()
        val steps = ascensionRows(fromPhase, toPhase)
        val b = GroupBuilder()
        steps.forEach { phase ->
            val row = table.firstOrNull { it.phase == phase } ?: return@forEach
            b.add(SHELL_CREDIT, SHELL_CREDIT, row.shellCredit)
            if (row.ascension1 > 0) b.add(CATEGORY_ASCENSION, weapon.ascension.at(0), row.ascension1)
            if (row.ascension2 > 0) b.add(CATEGORY_ASCENSION, weapon.ascension.at(1), row.ascension2)
            if (row.ascension3 > 0) b.add(CATEGORY_ASCENSION, weapon.ascension.at(2), row.ascension3)
            if (row.ascension4 > 0) b.add(CATEGORY_ASCENSION, weapon.ascension.at(3), row.ascension4)
            if (row.common1 > 0) b.add(CATEGORY_COMMON, weapon.common.at(0), row.common1)
            if (row.common2 > 0) b.add(CATEGORY_COMMON, weapon.common.at(1), row.common2)
            if (row.common3 > 0) b.add(CATEGORY_COMMON, weapon.common.at(2), row.common3)
            if (row.common4 > 0) b.add(CATEGORY_COMMON, weapon.common.at(3), row.common4)
        }
        return b.build()
    }

    fun buildCharacterMaterials(
        characterName: String,
        fromPhase: Int,
        toPhase: Int,
        skillFrom: Int,
        skillTo: Int,
    ): CalculatorResult {
        // Secondary Forte rows are included for their *own* range, not folded into
        // the skill range: they unlock on ascension, so a phase-0 -> 6 ascension
        // with an untouched skill slider still owes all four of them.
        val groups =
            mergeGroups(
                characterAscensionMaterials(characterName, fromPhase, toPhase) +
                    secondaryForteMaterials(characterName, fromPhase, toPhase) +
                    skillUpgradeMaterials(characterName, skillFrom, skillTo),
            )
        return CalculatorResult(
            characterName = characterName,
            groups = groups,
            materials = groups.flatMap { it.materials },
            totalItems = groups.sumOf { it.total },
        )
    }

    fun buildWeaponMaterials(
        weaponName: String,
        fromPhase: Int,
        toPhase: Int,
    ): CalculatorResult {
        val groups = mergeGroups(weaponAscensionMaterials(weaponName, fromPhase, toPhase))
        return CalculatorResult(
            weaponName = weaponName,
            groups = groups,
            materials = groups.flatMap { it.materials },
            totalItems = groups.sumOf { it.total },
        )
    }

    /**
     * Collapses buckets that share a category and sums repeated names within one.
     *
     * Summing by name *within* a category is safe and necessary: Shell Credit
     * accrues across every row, and a common drop appears in up to four rows.
     * Two different categories holding the same name are left apart on purpose —
     * they are different items that merely share a display name in the wiki data.
     */
    private fun mergeGroups(groups: List<MaterialGroup>): List<MaterialGroup> {
        val byCategory = LinkedHashMap<String, LinkedHashMap<String, Int>>()
        groups.forEach { group ->
            val bucket = byCategory.getOrPut(group.category) { LinkedHashMap() }
            group.materials.forEach { bucket[it.name] = (bucket[it.name] ?: 0) + it.quantity }
        }
        return byCategory.entries
            .filter { it.value.isNotEmpty() }
            .map { (category, items) ->
                MaterialGroup(
                    category = category,
                    materials = items.entries.map { MaterialItem(it.key, it.value) },
                )
            }
    }

    private fun List<String>.at(index: Int): String? = getOrNull(index)

    private class GroupBuilder {
        private val buckets = LinkedHashMap<String, LinkedHashMap<String, Int>>()

        fun add(
            category: String,
            name: String?,
            quantity: Int,
        ) {
            if (quantity <= 0 || name.isNullOrBlank()) return
            val bucket = buckets.getOrPut(category) { LinkedHashMap() }
            bucket[name] = (bucket[name] ?: 0) + quantity
        }

        fun build(): List<MaterialGroup> =
            buckets.map { (category, items) ->
                MaterialGroup(category, items.map { MaterialItem(it.key, it.value) })
            }
    }

    const val CATEGORY_LOCAL = "Local Speciality"
    const val CATEGORY_COMMON = "Common Materials"
    const val CATEGORY_BOSS = "Boss Material"
    const val CATEGORY_SKILL = "Skill Materials"
    const val CATEGORY_DROP = "Monster Drops"
    const val CATEGORY_ASCENSION = "Ascension Materials"
}
