#!/usr/bin/env python3
"""
Download upgrade-material icons from the Wuthering Waves wiki.

The wiki keeps every material as "Item <Name>.png" — the same file namespace
`tools/download_gacha_avatars.py` already reads for characters and weapons. This
script only pulls the material names, so the calculator can show an icon next to
each row instead of a bare text label.

The material list is derived from
`assets/config/calculator_materials.json` rather than hardcoded, which is the
whole point: that asset is regenerated by `tools/update_calculator_data.py`,
so re-running both scripts after a game update picks up new materials with no
code change.

Icons are downscaled to 128px WebP. The app renders them at 32-40dp, so the
wiki's full-size sprites would cost APK size for no visible gain.

Idempotent: an existing file is left alone unless --force is passed.

Usage:
    python3 tools/download_material_icons.py            # download what is missing
    python3 tools/download_material_icons.py --check    # report only
    python3 tools/download_material_icons.py --force    # re-download everything
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from io import BytesIO
from pathlib import Path

API = "https://wutheringwaves.fandom.com/api.php"
USER_AGENT = "WuWaConfig-material-icon-downloader/1.0 (on-device config tool)"
ASSET_PATH = Path("app/src/main/assets/config/calculator_materials.json")
OUTPUT_DIR = Path("app/src/main/assets/material_icons")

EXTENSION = ".webp"
MAX_SIZE = 128
WEBP_QUALITY = 82
BATCH = 40

# The wiki's file naming for materials. Verified against the live wiki: a
# material is "Item <Name>.png". "Material Shell Credit.png" also exists for
# Shell Credit alone, so the Item namespace is the one that covers everything.
ITEM_TEMPLATE = "Item {name}.png"

FILENAME_SAFE = re.compile(r"[^a-z0-9]+")


def api(params: dict) -> dict:
    query = urllib.parse.urlencode({**params, "format": "json", "formatversion": "2"})
    request = urllib.request.Request(
        f"{API}?{query}", headers={"User-Agent": USER_AGENT}
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def image_urls(file_names: list[str]) -> dict[str, str]:
    """Map wiki file name -> direct CDN URL, in batches."""
    urls: dict[str, str] = {}
    pending = list(file_names)
    while pending:
        batch, pending = pending[:BATCH], pending[BATCH:]
        data = api(
            {
                "action": "query",
                "prop": "imageinfo",
                "iiprop": "url",
                "titles": "|".join(f"File:{name}" for name in batch),
            }
        )
        for page in data["query"]["pages"]:
            info = page.get("imageinfo")
            if info:
                urls[page["title"].removeprefix("File:")] = info[0]["url"]
        time.sleep(0.2)
    return urls


def material_names(asset_path: Path) -> list[str]:
    """Every material the calculator can ever display, deduped and sorted.

    Derived from the asset rather than the wiki's item category on purpose: the
    calculator only ever needs icons for materials it can name, and a category
    crawl would pull several hundred icons the app never shows.

    Shell Credit is added explicitly. It is the one material the calculator
    invents rather than reads: `MaterialCalculator.SHELL_CREDIT` is a constant
    that appears in no cost table, so deriving names from the asset alone left it
    out and it rendered as the one icon-less row in every result. Any future
    calculator-side constant needs adding here too.
    """
    data = json.loads(asset_path.read_text(encoding="utf-8"))
    names: set[str] = {"Shell Credit"}

    def add(value: object) -> None:
        if isinstance(value, str) and value.strip():
            names.add(value.strip())

    for character in data.get("characters", {}).values():
        for key in ("boss", "local", "skillBoss"):
            add(character.get(key))
        for key in ("common", "wsm", "dwsm"):
            for entry in character.get(key) or []:
                add(entry)
    for weapon in data.get("weapons", {}).values():
        for key in ("ascension", "common"):
            for entry in weapon.get(key) or []:
                add(entry)

    return sorted(names)


def slug(name: str) -> str:
    """Filename-safe form of a material name.

    Strips every non-alphanumeric run to an underscore, so `Loong's Pearl` and
    `Daybreaker's Spine` become `loong_s_pearl` / `daybreaker_s_spine`. This
    matches PortraitAssets.normalizeKey in the app after punctuation removal,
    which is what the runtime lookup does.
    """
    return FILENAME_SAFE.sub("_", name.lower()).strip("_")


def download(url: str, destination: Path) -> bool:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=90) as response:
            raw = response.read()
        from PIL import Image

        with Image.open(BytesIO(raw)) as image:
            image = image.convert("RGBA")
            image.thumbnail((MAX_SIZE, MAX_SIZE), Image.LANCZOS)
            destination.parent.mkdir(parents=True, exist_ok=True)
            image.save(destination, "WEBP", quality=WEBP_QUALITY, method=6)
        return True
    except Exception as error:  # noqa: BLE001 - a failed icon must not stop the run
        print(f"    ! {destination.name}: {error}")
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report only, download nothing")
    parser.add_argument("--force", action="store_true", help="re-download even if present")
    args = parser.parse_args()

    if not ASSET_PATH.exists():
        print(
            f"{ASSET_PATH} not found — run tools/update_calculator_data.py first.",
            file=sys.stderr,
        )
        return 1

    names = material_names(ASSET_PATH)
    print(f"{len(names)} distinct materials referenced by the calculator")

    if not args.check:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        urls = image_urls([ITEM_TEMPLATE.format(name=name) for name in names])
    except Exception as error:  # noqa: BLE001
        print(f"Could not resolve image URLs: {error}", file=sys.stderr)
        return 1

    downloaded = skipped = failed = 0
    missing: list[str] = []

    for name in names:
        url = urls.get(ITEM_TEMPLATE.format(name=name))
        if url is None:
            missing.append(name)
            continue
        destination = OUTPUT_DIR / f"{slug(name)}.webp"
        if destination.exists() and not args.force:
            skipped += 1
            continue
        if args.check:
            downloaded += 1
            continue
        if download(url, destination):
            downloaded += 1
        else:
            failed += 1

    print()
    if args.check:
        print(f"Would download: {downloaded}  Already present: {skipped}  No wiki file: {len(missing)}")
    else:
        print(f"Downloaded: {downloaded}  Skipped: {skipped}  Failed: {failed}")
        if not missing:
            print("All referenced materials have an icon.")

    if missing:
        print(f"No wiki file for {len(missing)} material(s), e.g.:")
        for name in missing[:10]:
            print(f"  - {name}")

    # The completion claim is only meaningful if the on-disk count matches the
    # requested count. Printing "All referenced materials have an icon" while a
    # requested icon is absent is how Shell Credit ended up icon-less.
    if not args.check:
        on_disk = len(list(OUTPUT_DIR.glob(f"*{EXTENSION}")))
        print(f"On disk: {on_disk} icon(s) for {len(names)} material(s)")
        if on_disk < len(names):
            print(
                f"Note: {len(names) - on_disk} material(s) have no bundled icon; "
                "their rows render without one by design.",
                file=sys.stderr,
            )

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())