package com.wuwaconfig.app.model

data class LogInfo(
    val gpu: String? = null,
    val gpuFamily: String? = null,
    val gpuTier: String? = null,
    val glVersion: String? = null,
    val driverVersion: String? = null,
    val deviceModel: String? = null,
    val socName: String? = null,
    val socCode: String? = null,
    val cpuName: String? = null,
    val ramMb: Int? = null,
    val androidVersion: String? = null,
    val os: String? = null,
    val resolution: String? = null,
    val gameApi: String? = null,
    val api: String? = null,
    val vulkanStatus: String? = null,
    val deviceProfile: String? = null,
    val fpsCap: Int? = null,
    val fpsActual: Float? = null,
    val screenPct: Float? = null,
    val shadowQ: Int? = null,
    val qualityMode: String? = null,
    val kuroPostprocess: Int? = null,
    val isLowMem: Boolean? = null,
    val textureErrors: Int = 0,
    val gpuOom: Int = 0,
    val dropFrames: Int = 0,
    val forbiddenCvars: Int = 0,
    val thermalEvents: Int = 0,
    val networkErrors: Int = 0,
    val activeCvars: Map<String, String> = emptyMap(),
)
